package com.camera2rtsp

object WebControlHtml {
    fun build(): String {
        val sb = StringBuilder()
        sb.append("<!DOCTYPE html><html lang=\"pt-BR\">")
        sb.append("<head><meta charset=\"UTF-8\">")
        sb.append("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no\">")
        sb.append("<title>Camera2 RTMP Control</title>")
        sb.append("<style>")
        sb.append(":root{--bg:#0f172a;--surface:#1e293b;--surface2:#263348;--border:#334155;")
        sb.append("--accent:#38bdf8;--text:#f1f5f9;--muted:#94a3b8;")
        sb.append("--green:#10b981;--red:#ef4444;--yellow:#f59e0b;--purple:#a855f7;}")
        sb.append("*{margin:0;padding:0;box-sizing:border-box;-webkit-tap-highlight-color:transparent}")
        sb.append("html{font-size:14px}")
        sb.append("body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:var(--bg);color:var(--text);padding:10px;min-height:100vh}")
        sb.append(".container{max-width:900px;margin:0 auto}")
        sb.append(".header{text-align:center;margin-bottom:14px}")
        sb.append(".header h1{color:var(--accent);font-size:clamp(16px,5vw,24px);font-weight:800}")
        sb.append(".header p{color:var(--muted);font-size:11px;margin-top:3px}")
        sb.append(".statusbar{display:flex;flex-wrap:wrap;gap:6px;justify-content:center;padding:10px;background:var(--surface);border-radius:14px;border:1px solid var(--border);margin-bottom:14px}")
        sb.append(".badge{display:flex;align-items:center;gap:5px;background:var(--bg);padding:5px 11px;border-radius:20px;font-size:11px;font-weight:600;white-space:nowrap}")
        sb.append(".dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 6px var(--green);transition:background .3s}")
        sb.append(".dot.off{background:var(--red);box-shadow:0 0 6px var(--red)}")
        sb.append(".card{background:var(--surface);padding:14px;margin-bottom:12px;border-radius:14px;border:1px solid var(--border)}")
        sb.append(".card.hidden{display:none!important}")
        sb.append(".card h3{color:var(--accent);font-size:13px;font-weight:700;margin-bottom:11px}")
        sb.append(".val{display:inline-block;background:var(--bg);padding:2px 10px;border-radius:6px;font-weight:700;color:var(--accent);min-width:72px;text-align:center;font-size:12px}")
        sb.append(".info-row{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:6px}")
        sb.append(".info-pill{background:var(--bg);padding:4px 10px;border-radius:8px;font-size:11px;color:var(--muted)}")
        sb.append(".info-pill span{color:var(--text);font-weight:600}")
        sb.append(".btngroup{display:flex;flex-wrap:wrap;gap:7px}")
        sb.append("button{background:var(--surface2);color:var(--text);border:1px solid var(--border);padding:9px 13px;border-radius:10px;cursor:pointer;font-weight:600;font-size:12px;line-height:1.2;transition:background .15s,transform .1s;touch-action:manipulation;user-select:none;min-height:40px}")
        sb.append("button:hover{background:var(--accent);color:#0f172a;border-color:var(--accent)}")
        sb.append("button:active{transform:scale(.93)}")
        sb.append("button.active{background:var(--green);color:#fff;border-color:var(--green)}")
        sb.append("input[type=range]{width:100%;height:5px;background:var(--border);border-radius:4px;outline:none;-webkit-appearance:none;margin:10px 0;cursor:pointer}")
        sb.append("input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:24px;height:24px;background:var(--accent);cursor:grab;border-radius:50%;border:3px solid var(--bg);box-shadow:0 2px 6px rgba(0,0,0,.5)}")
        sb.append(".rlabels{display:flex;justify-content:space-between;font-size:10px;color:var(--muted);margin-top:2px}")
        sb.append(".toggle-row{display:flex;align-items:center;justify-content:space-between;padding:9px 0;border-bottom:1px solid var(--border)}")
        sb.append(".toggle-row:last-child{border-bottom:none}")
        sb.append(".toggle-label{font-size:13px;display:flex;align-items:center;gap:7px}")
        sb.append(".switch{position:relative;display:inline-block;width:46px;height:26px;flex-shrink:0}")
        sb.append(".switch input{opacity:0;width:0;height:0}")
        sb.append(".sw{position:absolute;cursor:pointer;inset:0;background:var(--border);border-radius:26px;transition:.3s}")
        sb.append(".sw:before{content:'';position:absolute;height:20px;width:20px;left:3px;bottom:3px;background:#fff;border-radius:50%;transition:.3s;box-shadow:0 1px 3px rgba(0,0,0,.4)}")
        sb.append("input:checked+.sw{background:var(--green)}")
        sb.append("input:checked+.sw:before{transform:translateX(20px)}")
        sb.append(".rtmp-input{width:100%;background:var(--bg);color:var(--text);border:1px solid var(--border);border-radius:8px;padding:9px 12px;font-size:12px;font-family:monospace;outline:none;margin-top:8px}")
        sb.append(".rtmp-input:focus{border-color:var(--accent)}")
        sb.append("@media(min-width:480px){.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}}")
        sb.append("#toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%) translateY(80px);padding:10px 22px;border-radius:24px;font-size:13px;font-weight:700;pointer-events:none;transition:transform .25s,opacity .25s;opacity:0;z-index:999;white-space:nowrap}")
        sb.append("#toast.show{transform:translateX(-50%) translateY(0);opacity:1}")
        sb.append("#toast.ok{background:var(--green);color:#fff}")
        sb.append("#toast.err{background:var(--red);color:#fff}")
        sb.append(".fps-row{display:flex;gap:6px;margin-top:8px}")
        sb.append(".fps-row button{flex:1;font-size:11px;padding:7px 4px}")
        sb.append("</style></head><body>")
        sb.append("<div class=\"container\">")
        sb.append("<div class=\"header\"><h1>Camera2 RTMP Control</h1>")
        sb.append("<p>Push RTMP para MediaMTX | Painel via Wi-Fi</p></div>")

        // Status bar
        sb.append("<div class=\"statusbar\">")
        sb.append("<div class=\"badge\"><span class=\"dot off\" id=\"dot-stream\"></span><span id=\"lbl-stream\">Conectando...</span></div>")
        sb.append("<div class=\"badge\">Cam: <span id=\"lbl-cam\">-</span></div>")
        sb.append("<div class=\"badge\">Res: <span id=\"lbl-res\">-</span></div>")
        sb.append("<div class=\"badge\">BR: <span id=\"lbl-br\">-</span> kbps</div>")
        sb.append("<div class=\"badge\">Lat: <span id=\"lbl-lat\">-</span></div>")
        sb.append("</div>")

        // RTMP URL
        sb.append("<div class=\"card\"><h3>Destino RTMP</h3>")
        sb.append("<input class=\"rtmp-input\" id=\"rtmp-url\" type=\"text\" value=\"rtmp://192.168.1.100:1935/live/stream\" placeholder=\"rtmp://IP:1935/live/stream\">")
        sb.append("<div class=\"btngroup\" style=\"margin-top:10px\">")
        sb.append("<button onclick=\"applyRtmpUrl()\">Aplicar URL</button>")
        sb.append("<button onclick=\"sendControl({streamAction:'start'},this,'Stream ON')\">Iniciar Stream</button>")
        sb.append("<button onclick=\"sendControl({streamAction:'stop'},this,'Stream OFF')\">Parar Stream</button>")
        sb.append("</div></div>")

        // Cameras
        sb.append("<div class=\"card\" id=\"card-camera\"><h3>Camera</h3>")
        sb.append("<div class=\"btngroup\" id=\"btngroup-camera\">Carregando...</div></div>")

        // Resolucao + Bitrate
        sb.append("<div class=\"grid2\">")
        sb.append("<div class=\"card\"><h3>Resolucao</h3>")
        sb.append("<div class=\"btngroup\" id=\"btngroup-resolution\" style=\"margin-bottom:10px\"></div>")
        sb.append("<div class=\"fps-row\" id=\"btngroup-fps\"></div></div>")
        sb.append("<div class=\"card\"><h3>Bitrate <span class=\"val\" id=\"br-value\">4000</span> kbps</h3>")
        sb.append("<input type=\"range\" id=\"bitrate\" min=\"500\" max=\"25000\" value=\"4000\" step=\"500\" oninput=\"updateBitrate(this.value)\">")
        sb.append("<div class=\"rlabels\"><span>500k</span><span>12M</span><span>25M</span></div>")
        sb.append("<div class=\"btngroup\" style=\"margin-top:8px\">")
        sb.append("<button onclick=\"setBitratePreset(2000)\">2M</button>")
        sb.append("<button onclick=\"setBitratePreset(4000)\">4M</button>")
        sb.append("<button onclick=\"setBitratePreset(8000)\">8M</button>")
        sb.append("<button onclick=\"setBitratePreset(20000)\">20M</button>")
        sb.append("</div></div></div>")

        // Zoom
        sb.append("<div class=\"card\" id=\"card-zoom\"><h3>Zoom <span class=\"val\" id=\"zoom-val\">1x</span></h3>")
        sb.append("<input type=\"range\" id=\"zoom\" min=\"0\" max=\"1\" value=\"0\" step=\"0.01\" oninput=\"updateZoom(this.value)\">")
        sb.append("<div class=\"rlabels\"><span>1x</span><span>Max</span></div>")
        sb.append("<div class=\"btngroup\" style=\"margin-top:8px\">")
        sb.append("<button onclick=\"setZoomPreset(0)\">1x</button>")
        sb.append("<button onclick=\"setZoomPreset(0.25)\">2x</button>")
        sb.append("<button onclick=\"setZoomPreset(0.5)\">4x</button>")
        sb.append("<button onclick=\"setZoomPreset(1.0)\">Max</button>")
        sb.append("</div></div>")

        // Foco
        sb.append("<div class=\"card\" id=\"card-focus\"><h3>Foco <span class=\"val\" id=\"focus-val\">Auto</span></h3>")
        sb.append("<input type=\"range\" id=\"focus\" min=\"0\" max=\"10\" value=\"0\" step=\"0.1\" oninput=\"updateFocus(this.value)\">")
        sb.append("<div class=\"rlabels\"><span>Auto/inf</span><span>Macro(10D)</span></div>")
        sb.append("<div class=\"btngroup\" style=\"margin-top:8px\" id=\"btngroup-focusmode\"></div>")
        sb.append("<button style=\"width:100%;margin-top:8px\" onclick=\"triggerAF(this)\">Tocar para Focar</button>")
        sb.append("</div>")

        // ISO + EV
        sb.append("<div class=\"grid2\">")
        sb.append("<div class=\"card\" id=\"card-iso\"><h3>ISO <span class=\"val\" id=\"iso-val\">50</span></h3>")
        sb.append("<input type=\"range\" id=\"iso\" min=\"0\" max=\"100\" value=\"0\" step=\"1\" oninput=\"updateISO(this.value)\">")
        sb.append("<div class=\"rlabels\"><span>50</span><span>1600</span><span>3200</span></div>")
        sb.append("<div class=\"toggle-row\" style=\"margin-top:6px\">")
        sb.append("<span class=\"toggle-label\">Sensor Manual</span>")
        sb.append("<label class=\"switch\"><input type=\"checkbox\" id=\"toggle-manual\" onchange=\"toggleManual(this)\"><span class=\"sw\"></span></label>")
        sb.append("</div></div>")
        sb.append("<div class=\"card\" id=\"card-ev\"><h3>EV <span class=\"val\" id=\"ev-val\">0</span></h3>")
        sb.append("<input type=\"range\" id=\"ev\" min=\"-8\" max=\"8\" value=\"0\" step=\"1\" oninput=\"updateEV(this.value)\">")
        sb.append("<div class=\"rlabels\"><span>-8</span><span>0</span><span>+8</span></div>")
        sb.append("<div class=\"toggle-row\" style=\"margin-top:8px\">")
        sb.append("<span class=\"toggle-label\">Travar AE</span>")
        sb.append("<label class=\"switch\"><input type=\"checkbox\" id=\"toggle-ae-lock\" onchange=\"toggleAELock(this)\"><span class=\"sw\"></span></label>")
        sb.append("</div></div></div>")

        // Branco + Extras
        sb.append("<div class=\"card\" id=\"card-wb\"><h3>Balanco de Branco</h3>")
        sb.append("<div class=\"btngroup\" id=\"btngroup-wb\"></div>")
        sb.append("<div class=\"toggle-row\" style=\"margin-top:8px\">")
        sb.append("<span class=\"toggle-label\">Travar AWB</span>")
        sb.append("<label class=\"switch\"><input type=\"checkbox\" id=\"toggle-awb-lock\" onchange=\"toggleAWBLock(this)\"><span class=\"sw\"></span></label>")
        sb.append("</div></div>")
        sb.append("<div class=\"card\" id=\"card-extras\"><h3>Controles Extras</h3>")
        sb.append("<div id=\"extras-flash\"></div>")
        sb.append("<div class=\"toggle-row\"><span class=\"toggle-label\">OIS (Otica)</span>")
        sb.append("<label class=\"switch\"><input type=\"checkbox\" id=\"toggle-ois\" onchange=\"toggleOIS(this)\"><span class=\"sw\"></span></label></div>")
        sb.append("<div class=\"toggle-row\"><span class=\"toggle-label\">EIS (Digital)</span>")
        sb.append("<label class=\"switch\"><input type=\"checkbox\" id=\"toggle-eis\" onchange=\"toggleEIS(this)\"><span class=\"sw\"></span></label></div>")
        sb.append("</div>")

        sb.append("<p style=\"text-align:center;margin-top:16px;color:var(--muted);font-size:10px;padding-bottom:20px\">Camera2 API / RootEncoder 2.6.1 / RTMP / MediaMTX</p>")
        sb.append("</div><div id=\"toast\" class=\"ok\">OK</div>")

        // JS
        sb.append("<script>")
        sb.append("var ISO_LIST=[50,100,200,400,800,1600,3200];")
        sb.append("var _caps=null,_pollFail=0,_toastTimer,_brT,_zT,_fT,_iT,_eT;")
        sb.append("function showToast(m,e){var t=document.getElementById('toast');t.textContent=m;t.className=e?'err show':'ok show';clearTimeout(_toastTimer);_toastTimer=setTimeout(function(){t.classList.remove('show');},1800);}")
        sb.append("function sendControl(d,btn,msg){fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(function(r){if(!r.ok)throw new Error(r.status);return r.json();}).then(function(){showToast(msg||'OK',false);}).catch(function(e){showToast('ERR:'+e.message,true);});}")
        sb.append("function markActive(attr,val){document.querySelectorAll('['+attr+']').forEach(function(el){el.classList.toggle('active',el.getAttribute(attr)===String(val));});}")
        sb.append("function applyRtmpUrl(){var v=document.getElementById('rtmp-url').value.trim();if(v)sendControl({rtmpUrl:v},null,'URL atualizada');}")
        sb.append("function updateBitrate(v){document.getElementById('br-value').textContent=v;clearTimeout(_brT);_brT=setTimeout(function(){sendControl({bitrate:+v},null,v+'kbps');},400);}")
        sb.append("function setBitratePreset(v){document.getElementById('bitrate').value=v;document.getElementById('br-value').textContent=v;sendControl({bitrate:v},null,v+'kbps');}")
        sb.append("function updateZoom(v){var m=(1+parseFloat(v)*7).toFixed(1);document.getElementById('zoom-val').textContent=m+'x';clearTimeout(_zT);_zT=setTimeout(function(){sendControl({zoom:parseFloat(v)},null,'Zoom '+m+'x');},150);}")
        sb.append("function setZoomPreset(v){document.getElementById('zoom').value=v;updateZoom(v);}")
        sb.append("function updateFocus(v){var f=parseFloat(v);document.getElementById('focus-val').textContent=f===0?'Auto':f.toFixed(1)+'D';clearTimeout(_fT);_fT=setTimeout(function(){sendControl({focus:f/10},null,f===0?'Auto':f.toFixed(1)+'D');},200);}")
        sb.append("function triggerAF(btn){sendControl({afTrigger:true},btn,'AF');}")
        sb.append("function updateISO(v){var iso=ISO_LIST[Math.min(+v,ISO_LIST.length-1)];document.getElementById('iso-val').textContent=iso;clearTimeout(_iT);_iT=setTimeout(function(){sendControl({iso:iso},null,'ISO '+iso);},350);}")
        sb.append("function updateEV(v){var n=+v;document.getElementById('ev-val').textContent=(n>0?'+':'')+n;clearTimeout(_eT);_eT=setTimeout(function(){sendControl({exposure:n},null,'EV '+n);},300);}")
        sb.append("function toggleManual(c){sendControl({manualSensor:c.checked},null,c.checked?'Manual ON':'Auto');}")
        sb.append("function toggleOIS(c){sendControl({ois:c.checked},null,c.checked?'OIS ON':'OIS OFF');}")
        sb.append("function toggleEIS(c){sendControl({eis:c.checked},null,c.checked?'EIS ON':'EIS OFF');}")
        sb.append("function toggleAELock(c){sendControl({aeLock:c.checked},null,c.checked?'AE Trav':'AE Livre');}")
        sb.append("function toggleAWBLock(c){sendControl({awbLock:c.checked},null,c.checked?'AWB Trav':'AWB Livre');}")
        sb.append("function setFocusMode(m){sendControl({focusmode:m},null,'Foco '+m);}")
        sb.append("function switchCamera(id){markActive('data-cam',id);sendControl({camera:id},null,'Cam '+id);}")
        sb.append("function setResolution(res,btn){markActive('data-res',res);sendControl({resolution:res},btn,res);}")
        sb.append("function setFPS(fps,btn){markActive('data-fps',fps);sendControl({fps:fps},btn,fps+' fps');}")

        sb.append("function pollStatus(){var t0=Date.now();fetch('/api/status').then(function(r){return r.json();}).then(function(d){")
        sb.append("var lat=Date.now()-t0;var c=d.curvals||{};_pollFail=0;")
        sb.append("document.getElementById('dot-stream').className='dot'+(d.streaming?'':' off');")
        sb.append("document.getElementById('lbl-stream').textContent=d.streaming?('RTMP: '+d.rtmp_url):'Parado';")
        sb.append("document.getElementById('lbl-cam').textContent=c.camera_id||'-';")
        sb.append("document.getElementById('lbl-res').textContent=c.video_size||'-';")
        sb.append("document.getElementById('lbl-br').textContent=c.bitrate_kbps||'-';")
        sb.append("document.getElementById('lbl-lat').textContent=lat+'ms';")
        sb.append("var u=document.getElementById('rtmp-url');if(u&&d.rtmp_url&&document.activeElement!==u)u.value=d.rtmp_url;")
        sb.append("var chkM=document.getElementById('toggle-manual');if(chkM)chkM.checked=c.manual_sensor==='on';")
        sb.append("var chkO=document.getElementById('toggle-ois');if(chkO)chkO.checked=c.ois==='on';")
        sb.append("var chkE=document.getElementById('toggle-eis');if(chkE)chkE.checked=c.eis==='on';")
        sb.append("var chkAE=document.getElementById('toggle-ae-lock');if(chkAE)chkAE.checked=c.ae_lock==='on';")
        sb.append("var chkAW=document.getElementById('toggle-awb-lock');if(chkAW)chkAW.checked=c.awb_lock==='on';")
        sb.append("if(c.bitrate_kbps){document.getElementById('br-value').textContent=c.bitrate_kbps;")
        sb.append("var bs=document.getElementById('bitrate');if(bs&&document.activeElement!==bs)bs.value=c.bitrate_kbps;}")
        sb.append("}).catch(function(){_pollFail++;if(_pollFail>=3){document.getElementById('dot-stream').className='dot off';document.getElementById('lbl-stream').textContent='Sem conexao';}});}")

        sb.append("function initCapabilities(){fetch('/api/capabilities').then(function(r){return r.json();}).then(function(caps){")
        sb.append("_caps=caps;var cg=document.getElementById('btngroup-camera');cg.innerHTML='';")
        sb.append("for(var i=0;i<caps.length;i++){(function(cap){if(cap.is_depth)return;")
        sb.append("var b=document.createElement('button');b.setAttribute('data-cam',cap.camera_id);")
        sb.append("b.textContent=cap.name||('Cam '+cap.camera_id);b.onclick=function(){switchCamera(cap.camera_id);};cg.appendChild(b);})(caps[i]);}")
        sb.append("var rg=document.getElementById('btngroup-resolution');rg.innerHTML='';")
        sb.append("var fc=null;for(var i=0;i<caps.length;i++){if(!caps[i].is_depth){fc=caps[i];break;}}")
        sb.append("if(fc&&fc.available_resolutions){")
        sb.append("var ps=[{res:'720p',key:'1280x720',lbl:'HD 720p'},{res:'1080p',key:'1920x1080',lbl:'FHD 1080p'},{res:'4k',key:'3840x2160',lbl:'4K'}];")
        sb.append("for(var j=0;j<ps.length;j++){(function(p){")
        sb.append("var found=fc.available_resolutions.indexOf(p.key)>=0;if(!found)return;")
        sb.append("var b=document.createElement('button');b.setAttribute('data-res',p.res);b.textContent=p.lbl;")
        sb.append("b.onclick=function(){setResolution(p.res,b);};rg.appendChild(b);})(ps[j]);}}")
        sb.append("var fg=document.getElementById('btngroup-fps');fg.innerHTML='';")
        sb.append("[15,24,30,60].forEach(function(fps){var b=document.createElement('button');")
        sb.append("b.setAttribute('data-fps',fps);b.textContent=fps+' fps';if(fps===30)b.classList.add('active');")
        sb.append("b.onclick=function(){setFPS(fps,b);};fg.appendChild(b);});")
        sb.append("var wg=document.getElementById('btngroup-wb');wg.innerHTML='';")
        sb.append("var fc2=caps[0];if(fc2&&fc2.supported_awb_modes){")
        sb.append("var wbN={'auto':'Auto','daylight':'Dia','cloudy':'Nublado','tungsten':'Tungst','incandescent':'Incand','fluorescent':'Fluor'};")
        sb.append("fc2.supported_awb_modes.forEach(function(mode){var b=document.createElement('button');")
        sb.append("b.setAttribute('data-wb',mode);b.textContent=wbN[mode]||mode;")
        sb.append("b.onclick=function(){markActive('data-wb',mode);sendControl({whiteBalance:mode},b,'WB '+mode);};")
        sb.append("wg.appendChild(b);});}")
        sb.append("var fc3=caps[0];if(fc3&&fc3.supported_af_modes){")
        sb.append("var fg2=document.getElementById('btngroup-focusmode');fg2.innerHTML='';")
        sb.append("var afN={'off':'Travar','auto':'Auto','continuous-video':'Continuo','continuous-picture':'Cont.Foto'};")
        sb.append("fc3.supported_af_modes.forEach(function(mode){var b=document.createElement('button');")
        sb.append("b.setAttribute('data-fm',mode);b.textContent=afN[mode]||mode;")
        sb.append("b.onclick=function(){markActive('data-fm',mode);setFocusMode(mode);};fg2.appendChild(b);});}")
        sb.append("}).catch(function(){console.warn('caps nao disponivel');});}")

        sb.append("initCapabilities();pollStatus();setInterval(pollStatus,2000);")
        sb.append("</script></body></html>")
        return sb.toString()
    }
}
